name: Build Plugins

on: [push, pull_request]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Clone RGB.NET
        uses: actions/checkout@v2
        with:
          repository: DarthAffe/RGB.NET
          path: RGB.NET
          ref: Development

      - name: Build RGB.NET
        run: dotnet build .\RGB.NET\RGB.NET.Core\RGB.NET.Core.csproj
      - run: dotnet build .\RGB.NET\RGB.NET.Layout\RGB.NET.Layout.csproj
      - run: dotnet build .\RGB.NET\RGB.NET.Presets\RGB.NET.Presets.csproj

      - name: Clone Artemis
        uses: actions/checkout@v2
        with:
          repository: Artemis-RGB/Artemis
          path: Artemis

      - name: Build Artemis
        run: dotnet build .\Artemis\src\Artemis.sln

      - name: Clone Plugins
        uses: actions/checkout@v2
        with:
          path: Plugins

      - name: Build Plugins
        run: dotnet publish -c Release .\Plugins\src\Artemis.Plugins.sln

        #msbuild is dumb so we have to upload one at a time :)
        #https://github.com/dotnet/sdk/issues/7238

      - name: Upload Discord
        uses: actions/upload-artifact@v2
        with:
          name: Discord
          path: .\Plugins\src\Artemis.Plugins.Modules.Discord\bin\x64\Release\net5.0-windows\publish

      - name: Upload OBS
        uses: actions/upload-artifact@v2
        with:
          name: OBS
          path: .\Plugins\src\Artemis.Plugins.Modules.OBS\bin\x64\Release\net5.0-windows\publish

      - name: Upload Spotify
        uses: actions/upload-artifact@v2
        with:
          name: Spotify
          path: .\Plugins\src\Artemis.Plugins.Modules.Spotify\bin\x64\Release\net5.0-windows\publish

      - name: Upload Chroma
        uses: actions/upload-artifact@v2
        with:
          name: Chroma
          path: .\Plugins\src\Artemis.Plugins.LayerBrushes.Chroma\bin\x64\Release\net5.0-windows\publish

      - name: Upload Gif
        uses: actions/upload-artifact@v2
        with:
          name: Gif
          path: .\Plugins\src\Artemis.Plugins.LayerBrushes.Gif\bin\x64\Release\net5.0-windows\publish

      - name: Upload Particle
        uses: actions/upload-artifact@v2
        with:
          name: Particle
          path: .\Plugins\src\Artemis.Plugins.LayerBrushes.Particle\bin\x64\Release\net5.0-windows\publish

      - name: Upload Fallout 4
        uses: actions/upload-artifact@v2
        with:
          name: Fallout4
          path: .\Plugins\src\Artemis.Plugins.Modules.Fallout4\bin\x64\Release\net5.0-windows\publish

      - name: Upload League of Legends
        uses: actions/upload-artifact@v2
        with:
          name: League Of Legends
          path: .\Plugins\src\Artemis.Plugins.Modules.LeagueOfLegends\bin\x64\Release\net5.0-windows\publish