name: Build Plugins

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone Plugins
        uses: actions/checkout@v3

      - name: Build Plugins
        run: dotnet publish -c Release src/Artemis.Plugins.diogotr7.sln

        #msbuild is dumb so we have to upload one at a time :)
        #https://github.com/dotnet/sdk/issues/7238

      - name: Upload Discord
        uses: actions/upload-artifact@v3
        with:
          name: Discord
          path: src/Artemis.Plugins.Modules.Discord/bin/x64/Release/net7.0/publish

      - name: Upload OBS
        uses: actions/upload-artifact@v3
        with:
          name: OBS
          path: src/Artemis.Plugins.Modules.OBS/bin/x64/Release/net7.0/publish

      - name: Upload Spotify
        uses: actions/upload-artifact@v3
        with:
          name: Spotify
          path: src/Artemis.Plugins.Modules.Spotify/bin/x64/Release/net7.0/publish

      - name: Upload Chroma
        uses: actions/upload-artifact@v3
        with:
          name: Chroma
          path: src/Artemis.Plugins.LayerBrushes.Chroma/bin/x64/Release/net7.0-windows/publish

      - name: Upload Gif
        uses: actions/upload-artifact@v3
        with:
          name: Gif
          path: src/Artemis.Plugins.LayerBrushes.Gif/bin/x64/Release/net7.0/publish

      - name: Upload Particle
        uses: actions/upload-artifact@v3
        with:
          name: Particle
          path: src/Artemis.Plugins.LayerBrushes.Particle/bin/x64/Release/net7.0/publish
          
      - name: Upload VoiceMeeter
        uses: actions/upload-artifact@v3
        with:
          name: VoiceMeeter
          path: src/Artemis.Plugins.Modules.VoiceMeeter/bin/x64/Release/net7.0/publish

      - name: Upload Ping
        uses: actions/upload-artifact@v3
        with:
          name: Ping
          path: src/Artemis.Plugins.Nodes.Ping/bin/x64/Release/net7.0/publish
